<?php
$animais = [
    'mamifero' => [
        'cachorro' => 'Óleo Motor',
        'gato' => 'Mimi',
        'passaro' => 'Lili',
        'elefante' => 'Juju',
        'leão' => 'Lili',
        'tigre' => 'Juju',
        'urso' => 'Lili',
        'baleia' => 'Juju',
        'golfinho' => 'Lili',
        'cavalo' => 'Juju',
        'vaca' => 'Lili',
        'ovelha' => 'Juju',
        'porco' => 'Lili',
        'rato' => 'Juju',
    ],
    'reptil' => [
        'cobra' => 'Juju',
        'lagarto' => 'Lili',
        'jacaré' => 'Juju',
        'iguana' => 'Lili',
        'tartaruga' => 'Juju',
        'crocodilo' => 'Lili',
        'lagartixa' => 'Juju',
        'camaleão' => 'Lili',
        'serpente' => 'Juju',
        'cascavel' => 'Lili',
        'jararaca' => 'Juju',
        'coral' => 'Lili',
    ],
    'anfibio' => [
        'sapo' => 'Juju',
        'rã' => 'Lili',
        'salamandra' => 'Juju',
        'girino' => 'Lili',
        'salamandra' => 'Juju',
        'perereca' => 'Lili',
        'sapo-cururu' => 'Juju',
        'sapo-de-chifre' => 'Lili'
    ],
    'peixe' => [
        'tubarão' => 'Juju',
        'baiacu' => 'Lili',
        'peixe-palhaço' => 'Juju',
        'peixe-gato' => 'Lili',
        'peixe-espada' => 'Juju',
        'peixe-lua' => 'Lili',
        'peixe-borboleta' => 'Juju'
    ],
    'inseto' => [
        'formiga' => 'Juju',
        'abelha' => 'Lili',
        'borboleta' => 'Juju',
        'libélula' => 'Lili',
        'joaninha' => 'Juju',
        'gafanhoto' => 'Lili',
        'mosca' => 'Juju',
        'barata' => 'Lili',
        'besouro' => 'Juju',
        'aranha' => 'Lili',
        'formiga-leão' => 'Juju',
        'formiga-carpinteira' => 'Lili'
    ],
    'ave' => [
        'falcão' => 'Juju',
        'coruja' => 'Lili',
        'pato' => 'Juju',
        'ganso' => 'Lili',
        'pinguim' => 'Juju',
        'gaivota' => 'Lili',
        'pavão' => 'Juju',
        'canário' => 'Lili',
        'periquito' => 'Juju'
    ],
    'aracnideo' => [
        'aranha' => 'Juju',
        'escorpião' => 'Lili',
        'caranguejo' => 'Juju',
        'lagosta' => 'Lili',
        'camarão' => 'Juju',
        'sirídeo' => 'Lili',
        'aranha-caranguejo' => 'Juju',
        'aranha-de-areia' => 'Lili'
    ],
];
